## Numpy module 
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.



In [52]:
import numpy as np

In [53]:
lst = list(range(1,25))
array = np.array(lst)
print(type(array))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [54]:
array = np.array([1,2,3,4])
array


array([1, 2, 3, 4])

In [55]:
lst = list(range(5))
print(lst)
print(array)

[0, 1, 2, 3, 4]
[1 2 3 4]


In [56]:
## arange() - used to create the array 
array = np.arange(1,25)
array  ## single dimensional array 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [57]:
# 2D array 
array = np.zeros((3,4))
array 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
## creating a 2D array 
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
## creating a 3d array 
array = np.array([[[1,2,3,3],[5,6,7,8],[1,3,4,5]],[[1,2,3,4],[1,2,3,4],[3,2,4,1]]])
array

array([[[1, 2, 3, 3],
        [5, 6, 7, 8],
        [1, 3, 4, 5]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [3, 2, 4, 1]]])

In [61]:
array = np.ones((3,4))
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
## linspace() - for equal spacing(used to create array in the equal interval) 
array = np.linspace(1,10,5)
array 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [63]:
array = np.linspace(2,20,10)
array

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [64]:
## reshape() = Returns a new array with the specified shape, reshaping the original array without changing its data.
array = np.linspace(1,10,5).reshape(5,1)
array

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [65]:
## convert 1d to 3d
array = np.arange(0,30)
array
array = np.arange(0,30).reshape(10,3)
array


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [66]:
## covert 1d tob 3d
array = np.arange(0,30)
array
array = np.arange(0,30).reshape(2,3,5)
array


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [67]:
array = np.arange(0,30)
array
array = np.arange(0,30).reshape(5,3,2)
array


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [68]:
## Random initialization 
array = np.random.randint(1,10,9)
array 

array([2, 1, 3, 4, 6, 6, 4, 8, 8])

In [69]:
array = np.random.randint(1,10,9).reshape(3,3)
array

array([[2, 9, 7],
       [8, 5, 5],
       [8, 6, 4]])

In [70]:
array = np.random.randint(1,10,(3,3))
array

array([[6, 2, 2],
       [5, 1, 6],
       [9, 4, 6]])

In [71]:
array = np.random.randint(10)
array

7

In [74]:
array = np.random.random(10)
array

array([0.89199899, 0.55885953, 0.12202742, 0.16842262, 0.02461156,
       0.9794002 , 0.51249796, 0.82789227, 0.04341274, 0.44700204])

In [79]:
array = np.arange(60).reshape(10,6)
array
array.dtype
array.ndim
array.size
array.shape


(10, 6)

In [80]:
array.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [87]:
lst = list[1,2,3,3,3]
lst

list[1, 2, 3, 3, 3]

In [92]:
lst = [[1,2,3],[4,5,6]]
array = np.array(lst)
array

array([[1, 2, 3],
       [4, 5, 6]])